# CPack properties
if(CPACK_BUILD_CONFIG MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  set_property(INSTALL "projectMSDL.exe" PROPERTY "CPACK_START_MENU_SHORTCUTS" "projectMSDL")
elseif(CPACK_BUILD_CONFIG MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  set_property(INSTALL "projectMSDL.exe" PROPERTY "CPACK_START_MENU_SHORTCUTS" "projectMSDL")
elseif(CPACK_BUILD_CONFIG MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  set_property(INSTALL "projectMSDL.exe" PROPERTY "CPACK_START_MENU_SHORTCUTS" "projectMSDL")
elseif(CPACK_BUILD_CONFIG MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  set_property(INSTALL "projectMSDL.exe" PROPERTY "CPACK_START_MENU_SHORTCUTS" "projectMSDL")
endif()
